version: '3.9'

services:
  vosk:
    image: sskorol/vosk-server:$TAG
    networks:
      - ai
    volumes:
      - ./model:/opt/vosk-server/model
    environment:
      - VOSK_SAMPLE_RATE=16000
      - PYTHONBUFFERED=1
      - PYTHONENCODING=utf-8
    ports:
      - "2700:2700"

networks:
  ai:
    driver: bridge
