FROM sskorol/vosk-api:0.3.27-pc

RUN mkdir /opt/vosk-server
COPY ./asr_server.py /opt/vosk-server
RUN pip3 install websockets asyncio

EXPOSE 2700
WORKDIR /opt/vosk-server

CMD ["python3", "./asr_server.py"]
